// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymuwzrrzbzhagrrenmby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdXd6cnJ6YnpoYWdycmVubWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjQ2NjksImV4cCI6MjA2Mjk0MDY2OX0.nC5wwBatfHv_lmTTqmMLIMbQHcDdqC7aavUOzYr7-AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);